### ISSUE TITLE
Hidden icons with default theme

### ISSUE THREAD

**Issue by marfago** [bluedynamics/yafowil.widget.array#1]
No icons are shown in array actions when the default theme is selected.
Adding a `&nbsp;` character in the innermost span would solve the issue.

**Comment by rnixx** [comment]
IIRC &nbsp has been removed because it made troubles with bootstrap theme. Best would be to fix this via CSS.

**Comment by marfago** [comment]
Yes. I solved adding this section in my css:

.icon-plus-sign:before {
    content:"\00a0";
}
.icon-minus-sign:before {
    content: "\00a0";
}
.icon-circle-arrow-up:before {
    content:"\00a0";
}
.icon-circle-arrow-down:before {
    content: "\00a0";
}

**Comment by rnixx** [comment]
can you create a pull request please?

**Comment by rnixx** [comment]
just pushed here https://github.com/bluedynamics/yafowil.widget.array/commit/a6eb0978ca4b76b2ebb28e3f88144bf4b0893bb4
